_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 41
                - 55
                - 105
            "2":
                - 1
                - 41
                - 55
                - 105
            "3":
                - 2
                - 23
                - 55
            "4": 3.8.10
            "5": 0.18.5
            "8":
                - 1
                - 5
            "12": 0.18.5
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 50
learning_rate:
    value: 0.01
optimizer:
    value: sgd
